application: gratisgear
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /css
  static_dir: css
- url: /server
  static_dir: server
- url: /fonts
  static_dir: fonts  
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /js/images
  static_dir: /js/images
- url: .*
  script: gratisgear.application

libraries:
- name: webapp2
  version: latest
